version: '3'

tasks:
  init:
    desc: Initialize Terraform
    cmds:
      - terraform init

  validate:
    desc: Validate Terraform configuration
    cmds:
      - terraform validate

  plan:
    desc: Plan Terraform configuration
    cmds:
      - terraform plan

  down:
    desc: Teardown Terraform infrastructure (force)
    cmds:
      - terraform destroy -target=google_cloud_run_v2_service.n8n_service -auto-approve || true
      - |
        if ! terraform destroy -auto-approve; then
          echo "Standard destroy failed, force deleting Cloud SQL instance..."
          gcloud sql instances delete n8n-db --quiet || true
          terraform destroy -auto-approve
        fi

  clean:
    desc: Remove temporarly files and terraform state locks
    cmds:
      - rm -rf .terraform
      - rm -f .terraform.lock.hcl
      - rm -rf .tmp/

  up:
    desc: Two-phase apply to configure N8N_HOST and WEBHOOK_URL after initial deployment
    silent: true
    cmds:
      - terraform apply -auto-approve
      - |
        N8N_URL=$(terraform output -raw n8n_url)
        if grep -q "^n8n_url" terraform.tfvars; then
          sed -i '' "s|^n8n_url.*|n8n_url = \"${N8N_URL}\"|" terraform.tfvars
        else
          printf '\nn8n_url = "%s"\n' "${N8N_URL}" >> terraform.tfvars
        fi
      - terraform apply -auto-approve

  lint:
    desc: Format and lint Terraform
    cmds:
      - terraform fmt -recursive
      - tflint --recursive
      - pre-commit run --all-files

  test:ci:
    desc: Run CI verification pipeline locally using act
    cmds:
      - act --validate
      - act

  ui:
    desc: Open n8n web UI in default browser
    vars:
      N8N_URL:
        sh: terraform output -raw n8n_url
    cmds:
      - open {{.N8N_URL}}

  logs:
    desc: View the latest logs for the n8n Cloud Run service
    vars:
      REGION:
        sh: terraform output -raw db_instance_connection_name | awk -F':' '{print $2}'
      PROJECT:
        sh: terraform output -raw db_instance_connection_name | awk -F':' '{print $1}'
    cmds:
      - gcloud run services logs read n8n --region={{.REGION}} --project={{.PROJECT}} --limit=50
